### PR TITLE
Handle incorrect logging due to mixup resulting from jenkins queues

### LINKED ISSUE #14: Handle wrong logs appearing due to job queues in jenkins
When the jenkins queues become long or are handled incorrectly, it is possible that the requestor side get the build message from an older jenkins build and process the logs from there, instead of a newer build that might have been queued by the requestor. This results in wrong logs being printed by requestor.

Proposed solution:
- cancel message to be sent from newer build, then if requestor already got the build num then update the newer build num. and tell user to ignore previous logs
- before sending the build num worker should check if a newer build exits in Jenkins before sending the build num. If yes then pause/cancel the old build and go forward with the new build.
- Increase the num of workers to avoid queuing

### PR DESCRIPTION
**Pull request by mohammedzee1000**
fix #14

### CODE REVIEW

File: pkg/jenkins/jenkins.go [hunk 1]
```diff
@@ -56,6 +56,34 @@ func CleanupOldBuilds(url, username, password, jobName string, currentBuild int,
...
+	if err != nil {
+		return false, fmt.Errorf("unable to initialize jenkins %w", err)
+	}
+	klog.V(2).Infof("Getting current jenkins job")
+	klog.V(3).Infof("job name %s", jobName)
+	job, err := jenkins.GetJob(jobName)
+	if err != nil {
+		return false, fmt.Errorf("failed to get job %s %w", jobName, err)
+	}
+	klog.V(2).Infof("getting builds in jenkins job job")
```
Comment (prietyc123) [inline pkg/jenkins/jenkins.go]: Typo `jenkins job job`

**Review by prietyc123 — CHANGES_REQUESTED** [review]

File: pkg/requestor/requestor.go [hunk 2]
```diff
@@ -83,51 +85,73 @@ func (r *Requestor) consumeMessages() error {
...
+					if m.IsLog() {
+						klog.V(2).Infof("received log message")
+						lm := messages.NewLogsMessage(-1, "", "")
+						err1 = json.Unmarshal(d.Body, lm)
+						if err1 != nil {
+							done <- fmt.Errorf("failed to unmarshal as logs message %w", err1)
+							return
+						}
+						klog.V(4).Infof("log message %#v", lm)
+						fmt.Println(lm.Logs)
```
Comment (prietyc123) [inline pkg/requestor/requestor.go:125]: Too many nested loop. Can't we customise it further.

**Review by prietyc123 — CHANGES_REQUESTED** [review]

File: pkg/worker/worker.go [hunk 3]
```diff
@@ -420,7 +441,15 @@ func (w *Worker) printBuildInfo() {
...
-	if err := w.cleanupOldBuilds(); err != nil {
+	err := w.checkForNewerBuilds()
+	if err != nil {
+		return false, err
+	}
+	err = w.sendCancelMessage()
+	if err != nil {
+		return false, fmt.Errorf("failed to send cancel message %w", err)
+	}
+	if err = w.cleanupOldBuilds(); err != nil {
```
Comment (anandrkskd) [inline pkg/worker/worker.go:458]: This is to check for new build and stop the ongoing build?

File: pkg/requestor/requestor.go [hunk 4]
```diff
@@ -83,51 +85,73 @@ func (r *Requestor) consumeMessages() error {
...
-					klog.V(4).Infof("log message %#v", lm)
-					fmt.Println(lm.Logs)
-				} else if m.IsStatus() {
-					klog.V(2).Infof("received status message")
-					sm := messages.NewStatusMessage(-1, false)
-					err1 = json.Unmarshal(d.Body, sm)
-					if err1 != nil {
-						done <- fmt.Errorf("failed to unmarshal as status message %w", err1)
+			//process message only if the jenkins projects match
+			if m.JenkinsProject == r.jenkinsProject {
```
Comment (anandrkskd) [inline pkg/requestor/requestor.go:89]: Will this also stop the condition in which test are triggered on the wrong project?

File: pkg/requestor/requestor.go (hunk 2 above)
Comment (mohammedzee1000) [reply pkg/requestor/requestor.go:125]: I dont think this is a nested loop at all. There is one loop that processes amqp deliveries. You could argue of course that there a depth in conditionals, which could maybe be optimized.

File: pkg/worker/worker.go (hunk 3 above)
Comment (mohammedzee1000) [reply pkg/worker/worker.go:458]: yes

File: pkg/requestor/requestor.go (hunk 4 above)
Comment (mohammedzee1000) [reply pkg/requestor/requestor.go:89]: Not the condition where tests are triggered on the wrong project but it will certainly ensure logs from the wrong project are not processed by the requestor. 

Basically, if a wrong project situation occurs (which should not as queues are separate, unless args were passed incorrectly) this time, it will timeout rather than show wrong logs

File: pkg/jenkins/jenkins.go (hunk 1 above)
Comment (mohammedzee1000) [reply pkg/jenkins/jenkins.go]: fixing, will push commit shortly

File: pkg/requestor/requestor.go (hunk 4 above)
Comment (mohammedzee1000) [reply pkg/requestor/requestor.go:89]: https://github.com/mohammedzee1000/ci-firewall/pull/15/commits/abc6edc51fd5e25894d4e7ee1dde67e2e57e4f71 should ensure build does not get triggered at all if project name is mismatched

File: pkg/requestor/requestor.go (hunk 2 above)
Comment (prietyc123) [reply pkg/requestor/requestor.go:125]: > You could argue of course that there a depth in conditionals, which could maybe be optimized.

yes, that's where I was also concerned.
